### ISSUE TITLE
SpotX-Bash not working on Apple Silicon

### ISSUE THREAD

**Issue by divinedivinityy** [jetfir3/SpotX-Bash#10]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have re-installed Spotify and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.2.9.743.g85d9593d
- OS: macOS Monterey v12.5
- Shell: zsh
```

### 📝 Description

1. Closed _**old spotify version**_
2. Reopened and got **_crash report every time_**
3. Tried to re-paste the startup command in Terminal
4. **_Re-installed Spotify and SpotxBash to newest version_**
5. More Repeated crash reports

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://gist.github.com/jetfir3/e8830cf8deba6a4f15eec094d344f7b1/raw/spotx.sh)
Everything loaded into Terminal like normal

**Comment by jetfir3** [comment]
> * Closed _**old spotify version**_
> * Reopened and got **_crash report every time_**

I'm a bit unsure of your description points #1 and #2...

- Does 1.2.9.743.g85d9593d crash even without patching w/SpotX-Bash?
- Did Spotify update itself to 1.2.9.743.g85d9593d and then crash?
- Or did you update to 1.2.9.743.g85d9593d, repatch with SpotX-Bash and then the crashing started? 

I've received a few reports from Apple Silicon users about this issue and I'm trying to narrow down if this is Spotify related or SpotX-Bash related. Some of the same users who reported crashing on Apple Silicon said the same version worked without issue on their Intel machines.

**Comment by divinedivinityy** [comment]
I didn't update anything until I re-installed and I could tell it was crashing because of spotx-bash since when I re-installed the same thing happened-

**Comment by divinedivinityy** [comment]
> I didn't update anything until I re-installed and I could tell it was crashing because of spotx-bash since when I re-installed the same thing happened-

I forgot to mention I deleted spotx-bash after updating and it worked perfectly fine so that's why I knew lol

**Comment by jetfir3** [comment]
Ok, so..
Spotify 1.2.9.743 opens fine before applying SpotX-Bash. And after running the Spot-Bash command, Spotify then crashes?

Can you try running the SpotX-Bash command again and letting me know if it still crashes for you?

**Comment by divinedivinityy** [comment]
Yes I'll see if it crashes again give me a few

**Comment by divinedivinityy** [comment]
Ok this time it gave me an error 
<img width="588" alt="Screen Shot 2023-04-14 at 8 54 00 PM" src="https://user-images.githubusercontent.com/130804608/232175113-24587d20-956c-497a-a95b-3f25f762d7b3.png">

**Comment by divinedivinityy** [comment]
> Ok this time it gave me an error <img alt="Screen Shot 2023-04-14 at 8 54 00 PM" width="588" src="https://user-images.githubusercontent.com/130804608/232175113-24587d20-956c-497a-a95b-3f25f762d7b3.png">

((I have not modified my spotify btw))

**Comment by jetfir3** [comment]
Reinstall spotify with SpotX-Bash.. it should download, install and patch it if all goes as planned. 

```
bash <(curl -sSL https://gist.github.com/jetfir3/e8830cf8deba6a4f15eec094d344f7b1/raw/spotx.sh) --installclient
```

**Comment by divinedivinityy** [comment]
It reopened and its no longer crashing or giving any errors but when spotify opens it doesn't disable the ads or load in any modifications it just shows the normal spotify

**Comment by jetfir3** [comment]
I don't know what's going on at this point then.

```
bash <(curl -sSL https://gist.github.com/jetfir3/e8830cf8deba6a4f15eec094d344f7b1/raw/spotx.sh) -f
```

the above command forces re-patching Spotify with SpotX-Bash... what happpens? post terminal output too please.

**Comment by divinedivinityy** [comment]
<img width="588" alt="Screen Shot 2023-04-14 at 9 17 14 PM" src="https://user-images.githubusercontent.com/130804608/232176225-6908f61d-3529-4ad4-af17-23520ce03a9c.png">
<img width="1440" alt="Screen Shot 2023-04-14 at 9 17 39 PM" src="https://user-images.githubusercontent.com/130804608/232176226-f2bd0f29-261c-4cd7-8cb9-6dc214d39a26.png">
I wish I could say it worked but still nothing happens other than spotx closing spotify after pasting that into terminal

**Comment by divinedivinityy** [comment]
> <img alt="Screen Shot 2023-04-14 at 9 17 14 PM" width="588" src="https://user-images.githubusercontent.com/130804608/232176225-6908f61d-3529-4ad4-af17-23520ce03a9c.png">
> 
> <img alt="Screen Shot 2023-04-14 at 9 17 39 PM" width="1440" src="https://user-images.githubusercontent.com/130804608/232176226-f2bd0f29-261c-4cd7-8cb9-6dc214d39a26.png">
> 
> I wish I could say it worked but still nothing happens other than spotx closing spotify after pasting that into terminal

Is it possible that spotify added any new things that could potentially block the program? I used to use better discord alot and that always happened to them

**Comment by jetfir3** [comment]
It seems as if nothing is being patched at all for some reason.

I will try to sort this out in our telegram group with the users there and update this issue if/when things get fixed.

**Comment by divinedivinityy** [comment]
> It seems as if nothing is being patched at all for some reason.
> 
> I will try to sort this out in our telegram group with the users there and update this issue if/when things get fixed.

Alright thank you for your help!

**Comment by jetfir3** [comment]
This issue should now be resolved. 

Running the SpotX-Bash command on a fresh Spotify install should now work without issue.

Anyone who has not run into this issue yet should be able to continue their usual SpotX-Bash usage without any interruption.

**Comment by divinedivinityy** [comment]
> This issue should now be resolved.
> 
> Running the SpotX-Bash command on a fresh Spotify install should now work without issue.
> 
> Anyone who has not run into this issue yet should be able to continue their usual SpotX-Bash usage without any interruption.

Yes its working now for me thanks again
