### ISSUE TITLE
No longer working on my mac.

### ISSUE THREAD

**Issue by ibrhmch** [jetfir3/SpotX-Bash#14]
This happened today, I have something similar on my iPhone too and I'm getting ads there too. It seems like spotify might have found a way to show us ads through some sort of server side changes.

**Comment by jetfir3** [comment]
Start a new issue and properly fill out a bug report with as much info/details as possible + screenshots of ads... all done after a complete uninstall of Spotify and fresh re-install of Spotify/SpotX-Bash.
