### ISSUE TITLE
better comand

### ISSUE THREAD

**Issue by pacchio1** [jetfir3/SpotX-Bash#26]
bash <(curl -sSL https://spotx-official.github.io/run.sh) -> 
curl -sSL https://spotx-official.github.io/run.sh | bash

more compatible with all terminals.

**Comment by jetfir3** [comment]
@pacchio1 this is already covered in the FAQ - https://github.com/SpotX-Official/SpotX-Bash/wiki/SpotX%E2%80%90Bash-FAQ#why-doesnt-spotx-bash-work-with-my-shell

using arguments/options/flags with that method becomes more annoying. For the minority who are not using bash-compliant shells, they have the option to use the other command.
