### ISSUE TITLE
Not able to apply SpotX-Bash

### ISSUE THREAD

**Issue by Aquavortqx** [jetfir3/SpotX-Bash#8]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have re-installed Spotify and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify version: spotify 1:1.1.84.716-13
- OS: CachyOS Linux x86_64
- Shell: fish 3.6.0
```

### 📝 Description

1.Download the specified version of spotify from the arch aur repo using git clone command and makepkg -si
2.Run the command `bash <(curl -sSL https://gist.github.com/jetfir3/e8830cf8deba6a4f15eec094d344f7b1/raw/spotx.sh) --disablesidebarlyrics -p` 
   to install spotx-bash
3.The shell comes out with an error.
...

### 🖥️ Terminal Input/Output

Terminal Input 

`bash <(curl -sSL https://gist.github.com/jetfir3/e8830cf8deba6a4f15eec094d344f7b1/raw/spotx.sh) --disablesidebarlyrics -p`

Terminal Output

`fish: Invalid redirection target:
bash <(curl -sSL https://gist.github.com/jetfir3/e8830cf8deba6a4f15eec094d344f7b1/raw/spotx.sh) --disablesidebarlyrics -p
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^`

**Comment by jetfir3** [comment]
This isn't a spotx-bash issue but a matter of your shell not handling the suggested command formatting.

A quick google would have pointed you here to explain - https://github.com/fish-shell/fish-shell/issues/5181

You may have to play around with formatting to get the additional arguments sorted as well.

**Comment by jetfir3** [comment]
I finally broke down and added proper support for the pipe-style launch command. While the command already worked for normal SpotX-Bash usage, interactive prompts could not reliably read input because the script itself occupied stdin. That is now handled correctly, and the alternative command is mentioned in the `README`.

https://github.com/SpotX-Official/SpotX-Bash/commit/230b7510ff28cf2b019be362def8c8c804770516
